### PR TITLE
Script improvements

### PR DESCRIPTION
**Pull request by ashetkar**
- Allow users to specify local or remote snappydata build which will be used to launch the cluster on AWS.
- Use latest Amazon Linux AMIs (2018.03).
- Install snappydata at /opt/snappydata which is consistent with snappydata AMIs.
- Configure heap size only if not configured via command line.
- Use private IPs of the EC2 instances while configuring the cluster so that it'll be accessible across restarts.
- Allow users to specify conf properties in the command line itself. Discontinued the need to specify actual conf files.
- Disable --enterprise option. Users can now download enterprise tarball and specify it in the command line.
- Allow users to choose snappydata OSS version (1.0.0/1.0.1/1.0.2)
- Error out if there are no nodes to stop or terminate.
- Delete the security groups by default when the cluster is terminated.
- Doc updates in snappydata repository: https://github.com/SnappyDataInc/snappydata/pull/1179

### CODE REVIEW

**Review by kneeraj — COMMENTED** [review]
Bunch of improvements and ideas discussed. Amogh to file a task in JIRA for the same.
May be the change for specifying separate root_ebs_volume for locators, servers and leads should be added as locators is not going to use that mush space as servers.
Rest of the improvements can be done in a subsequent checkin after discussing the points with a wider group.

**Comment by ashetkar** [comment]
Merging this PR. More improvements tracked under SNAP-2622.

**Comment by jramnara** [comment]
wasn't there a bug in the script for cluster delete that tibco reported ? if you specify the wrong zone the script silently returns. The user assumed his cluster was deleted.

**Comment by ashetkar** [comment]
Yes. This is fixed with this PR, which is now in master. Mentioned it as below point in the description.
- Error out if there are no nodes to stop or terminate.

**Pull request merged**
